apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-config
  labels:
    {{- include "chart.labels" . | indent 4}}
{{/*    {{- template "chart.labels" . }}*/}}

data:
  date: {{ now | date "2006-01-02" | quote}}
  {{- if eq .Values.env "production"}} # "-" for delete extra line
  paymentToken: "1234"
  {{- else}}
  paymentToken: false
  {{- end}}
  {{- with  .Values.value.requirements.limits}}
  memory: {{.memory}}
  version: {{$.Values.value.requirements.limits.cpu}}
  cpu: {{.cpu}}
  {{- end}}
  {{- $map := .Release.Name | upper | quote}} # Variable
  map: {{ $map}}
{{/*  users:*/}}
{{/*    {{- range $index, $user := .Values.users}} # same as .map((user, index)=>user.name ...)*/}}
{{/*    - {{$user.name}}:"{{$user.role}} - {{$index}}"*/}}
{{/*    {{- end}}*/}}
  users: |-
    {{- range  tuple "Anton" "Vasia"}}
    - {{.}}
    {{- end}}